#!/usr/bin/env python
"""Generate AGENTS.md from CLAUDE.md (single source of truth).

`AGENTS.md` is the cross-tool agent guide; we keep one authored file
(`CLAUDE.md`) and derive `AGENTS.md` from it with a "do not edit" banner so the
two never drift. CI runs this with `--check` and fails the PR on drift.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLAUDE = ROOT / "CLAUDE.md"
AGENTS = ROOT / "AGENTS.md"

BANNER = (
    "<!--\n"
    "  AGENTS.md is auto-generated from CLAUDE.md by scripts/sync_agents_md.py.\n"
    "  Do NOT edit this file directly — edit CLAUDE.md and run\n"
    "  `uv run python scripts/sync_agents_md.py` to regenerate. CI fails the PR\n"
    "  if this file drifts from CLAUDE.md (see .github/workflows/lint.yml).\n"
    "-->\n\n"
)


def render() -> str:
    return BANNER + CLAUDE.read_text(encoding="utf-8")


def main() -> int:
    want = render()
    if "--check" in sys.argv:
        current = AGENTS.read_text(encoding="utf-8") if AGENTS.exists() else ""
        if current != want:
            print("AGENTS.md is out of sync with CLAUDE.md. Run scripts/sync_agents_md.py.")
            return 1
        print("AGENTS.md is in sync.")
        return 0
    AGENTS.write_text(want, encoding="utf-8")
    print(f"Wrote {AGENTS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
